name: interact
description: A collection of customizable interactive command-line components.
version: 2.2.0
publish_to: none

environment:
  sdk: ^3.11.4

dependencies:
  dart_console: any
  meta: any
  tint: any

dev_dependencies:
  lints: any
