name: Build Windows

on:
  release:
    types:
      - created
  workflow_dispatch:
    inputs:
      version:
        description: cli version e.g. 1.0.0
        type: string
        required: true
      prerelease:
        type: boolean
        default: false

permissions:
  contents: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  prerelease: ${{ inputs.prerelease || github.event.release.prerelease }}
  release_base_url: ${{ github.server_url }}/${{ github.repository }}/releases
  setuparm64: discloud-cli-x64-setup.exe
  setupx64: discloud-cli-x64-setup.exe
  version: ${{ inputs.version || github.ref_name }}

jobs:
  build:
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        include:
          - os: windows-latest
            target_os: windows
            target_arch: x64
          - os: windows-11-arm
            target_os: windows
            target_arch: arm64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get artifacts
        continue-on-error: true
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Get dependencies
        run: dart pub get

      - name: Prepare pubspec
        run: dart run scripts/prepare_pubspec.dart --version ${{ env.version }}

      - name: Run build runner
        run: dart run build_runner build -r -v --low-resources-mode

      - name: Dart format
        run: |
          dart format .
          dart fix --apply

      - name: Compile
        run: dart compile exe lib/main.dart -o discloud-cli-${{ matrix.target_arch }}.exe --target-os=${{ matrix.target_os }} --target-arch=${{ matrix.target_arch }}

      - name: Save artifacts
        uses: actions/upload-artifact@v7
        with:
          if-no-files-found: error
          name: ${{ env.version }}
          overwrite: true
          retention-days: 1
          path: ./*.exe

  setup:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Get dependencies
        run: dart pub get

      - name: Prepare inno setup
        run: dart run scripts/prepare_inno_setup.dart --version ${{ env.version }}

      - name: Generate docs
        run: dart run scripts/docs/generate.dart

      - name: Get artifacts
        uses: actions/download-artifact@v8
        with:
          name: ${{ env.version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Build setup
        run: iscc inno_setup.iss

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ env.prerelease }}
          tag_name: ${{ env.version }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./*-setup.exe

  winget:
    needs: setup
    runs-on: windows-latest

    steps:
      - name: Install Inno Setup
        run: winget install Microsoft.WingetCreate -h --accept-package-agreements --accept-source-agreements --nowarn --verbose

      - name: Submit using wingetcreate
        run: wingetcreate update Discloud.CLI -s -v ${{ env.version }} --release-notes-url ${{ env.release_base_url }}/tag/${{ env.version }} -u '${{ env.release_base_url }}/download/${{ env.version }}/${{ env.setupx64 }}|x64' '${{ env.release_base_url }}/download/${{ env.version }}/${{ env.setuparm64 }}|arm64' -t ${{ secrets.PERSONAL_GITHUB_TOKEN }}
