name: Build Linux & MacOS

on:
  release:
    types:
      - created
  workflow_dispatch:
    inputs:
      version:
        description: cli version e.g. 1.0.0
        type: string
        required: true
      prerelease:
        type: boolean
        default: false

permissions:
  contents: write
  actions: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Get dependencies
        run: dart pub get

      - name: Upgrade pubspec version
        run: dart run scripts/upgrade_pubspec_version.dart --version ${{ inputs.version || github.ref_name }}

      - name: Run build runner
        run: dart run build_runner build -drv --low-resources-mode

      - name: Generate docs
        run: dart run scripts/docs/generate.dart

      - name: Dart format
        run: |
          dart format .
          dart fix --apply

      - name: Compile
        run: |
          dart compile exe lib/main.dart -o discloud-cli-macos-arm64 --target-os=macos --target-arch=arm64
          dart compile exe lib/main.dart -o discloud-cli-linux-arm64 --target-os=linux --target-arch=arm64
          dart compile exe lib/main.dart -o discloud-cli-linux-x64 --target-os=linux --target-arch=x64

      - name: Save artifacts
        uses: actions/upload-artifact@v7
        with:
          if-no-files-found: error
          name: ${{ inputs.version || github.ref_name }}
          overwrite: true
          retention-days: 1
          path: |
            discloud-cli-macos-arm64
            discloud-cli-linux-arm64
            discloud-cli-linux-x64

  archive:
    needs: build
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - target_os: macos
            target_arch: arm64
          - target_os: linux
            target_arch: arm64
          - target_os: linux
            target_arch: x64

    runs-on: macos-latest
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.version || github.ref_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare archive
        run: |
          mkdir discloud
          cp discloud-cli-${{ matrix.target_os }}-${{ matrix.target_arch }} discloud/discloud
          tar -czf discloud-cli-${{ matrix.target_os }}-${{ matrix.target_arch }}.tar.gz discloud
          rm -f discloud/discloud

      - name: Generate SHA256
        id: sha
        run: |
          echo "sha256=$(shasum -a 256 discloud-cli-${{ matrix.target_os }}-${{ matrix.target_arch }}.tar.gz | awk '{print $1}')" >> $GITHUB_OUTPUT

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ inputs.prerelease || github.event.release.prerelease }}
          tag_name: ${{ inputs.version || github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            discloud-cli-${{ matrix.target_os }}-${{ matrix.target_arch }}
            discloud-cli-${{ matrix.target_os }}-${{ matrix.target_arch }}.tar.gz

      - name: Debug SHA
        run: echo "discloud-cli-${{ matrix.target_os }}-${{ matrix.target_arch }}.tar.gz=${{ steps.sha.outputs.sha256 }}"
