name: Build Windows

on:
  release:
    types:
      - created
  workflow_dispatch:
    inputs:
      version:
        description: cli version e.g. 1.0.0
        type: string
        required: true
      prerelease:
        type: boolean
        default: false

permissions:
  contents: write
  actions: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        include:
          - os: windows-latest
            target_os: windows
            target_arch: x64
          - os: windows-11-arm
            target_os: windows
            target_arch: arm64

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Get artifacts
        continue-on-error: true
        uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.version || github.ref_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Get dependencies
        run: dart pub get

      - name: Prepare pubspec
        run: dart run scripts/prepare_pubspec.dart --version ${{ inputs.version || github.ref_name }}

      - name: Run build runner
        run: dart run build_runner build -drv --low-resources-mode

      - name: Dart format
        run: |
          dart format .
          dart fix --apply

      - name: Compile
        run: |
          dart compile exe lib/main.dart -o discloud-cli-${{ matrix.target_arch }}.exe --target-os=${{ matrix.target_os }} --target-arch=${{ matrix.target_arch }}

      - name: Save artifacts
        uses: actions/upload-artifact@v7
        with:
          if-no-files-found: error
          name: ${{ inputs.version || github.ref_name }}
          overwrite: true
          retention-days: 1
          path: ./*.exe

  setup:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Get dependencies
        run: dart pub get

      - name: Prepare inno setup
        run: dart run scripts/prepare_inno_setup.dart --version ${{ inputs.version || github.ref_name }}

      - name: Generate docs
        run: dart run scripts/docs/generate.dart

      - name: Get artifacts
        uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.version || github.ref_name }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Build setup
        run: iscc inno_setup.iss

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: ${{ inputs.prerelease || github.event.release.prerelease }}
          tag_name: ${{ inputs.version || github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: ./*.exe

  winget:
    needs: setup
    runs-on: windows-latest
    steps:
      - name: Install Winget Create
        run: choco install wingetcreate -y
      - name: Submit using wingetcreate
        run: wingetcreate update Discloud.CLI -s -v ${{ inputs.version || github.ref_name }} -u https://github.com/discloud/cli-dart/releases/download/${{ inputs.version || github.ref_name }}/discloud-cli-x64-setup.exe -t ${{ secrets.PERSONAL_GITHUB_TOKEN }}
