name: update docs

on:
  push:
    paths-ignore:
      - docs

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      - name: Get short SHA
        id: short_github_sha
        run: |
          id=$(echo ${{ github.sha }} | cut -c 1-7)
          echo "id=$id" >> $GITHUB_OUTPUT

      - name: Get dependencies
        run: dart pub get

      - name: Run build runner
        run: dart run build_runner build -r -v --low-resources-mode

      - name: Generate docs
        run: dart scripts/docs/generate.dart

      - name: Git diff
        id: diff
        continue-on-error: true
        run: git diff --quiet

      - name: Git config
        if: steps.diff.outcome == 'failure'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Git push in new branch
        if: steps.diff.outcome == 'failure'
        run: |
          git checkout -b docs/update
          git add docs
          git commit -m "docs: update ${{ steps.short_github_sha.outputs.id }}"
          git push --set-upstream origin docs/update

      - name: Git create & merge pull request
        if: steps.diff.outcome == 'failure'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create -t "docs: update ${{ steps.short_github_sha.outputs.id }}" -b " "
          gh pr merge -ds
